# Generated by Django 6.0.7 on 2026-08-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('whatsapp', 'WhatsApp Order')], default='cod', max_length=20),
        ),
    ]
